

# ------------------------------------------------------------------------------------------
# Six languages, the English text as the key: each line gives fr, de, es, pt, ru
# ------------------------------------------------------------------------------------------

_T = {
 "today": ("aujourd'hui", "heute", "hoy", "hoje", "сегодня"),
 "yesterday": ("hier", "gestern", "ayer", "ontem", "вчера"),
 "cannot reach the server": ("serveur injoignable", "server nicht erreichbar", "no se puede alcanzar el servidor", "não é possível contactar o servidor", "сервер недоступен"),
 "wrong username or password": ("identifiant ou mot de passe incorrect", "benutzername oder passwort falsch", "usuario o contraseña incorrectos", "utilizador ou palavra-passe errados", "неверное имя пользователя или пароль"),
 "not a WebDAV folder at this address": ("pas de dossier WebDAV à cette adresse", "kein WebDAV-ordner unter dieser adresse", "no hay carpeta WebDAV en esta dirección", "não há pasta WebDAV neste endereço", "по этому адресу нет папки WebDAV"),
 "no reading model for %1 — it could not be downloaded": ("pas de modèle de lecture pour %1 — il n'a pas pu être téléchargé", "kein lesemodell für %1 — es konnte nicht geladen werden", "no hay modelo de lectura para %1 — no se pudo descargar", "não há modelo de leitura para %1 — não foi possível descarregá-lo", "нет модели чтения для %1 — не удалось загрузить"),
 "Tesseract is not installed: the pages are kept without their text": ("Tesseract n'est pas installé : les pages sont gardées sans leur texte", "Tesseract ist nicht installiert: die seiten bleiben ohne text", "Tesseract no está instalado: las páginas se guardan sin su texto", "O Tesseract não está instalado: as páginas ficam sem texto", "Tesseract не установлен: страницы сохраняются без текста"),
 "the feeder is empty": ("le chargeur est vide", "der einzug ist leer", "el alimentador está vacío", "o alimentador está vazio", "лоток подачи пуст"),
 "this scanner has no feeder": ("ce scanner n'a pas de chargeur", "dieser scanner hat keinen einzug", "este escáner no tiene alimentador", "este digitalizador não tem alimentador", "у этого сканера нет лотка подачи"),
 "this scanner cannot scan both sides": ("ce scanner ne scanne pas le recto verso", "dieser scanner kann nicht beidseitig scannen", "este escáner no escanea a doble cara", "este digitalizador não digitaliza frente e verso", "этот сканер не сканирует обе стороны"),
 "the scanner is not answering — is it switched on?": ("le scanner ne répond pas — est-il allumé ?", "der scanner antwortet nicht — ist er eingeschaltet?", "el escáner no responde — ¿está encendido?", "o digitalizador não responde — está ligado?", "сканер не отвечает — он включён?"),
 "the scanner is busy": ("le scanner est occupé", "der scanner ist beschäftigt", "el escáner está ocupado", "o digitalizador está ocupado", "сканер занят"),
 "the scanner's cover is open": ("le capot du scanner est ouvert", "die abdeckung des scanners ist offen", "la tapa del escáner está abierta", "a tampa do digitalizador está aberta", "крышка сканера открыта"),
 "paper jam in the scanner": ("bourrage papier dans le scanner", "papierstau im scanner", "atasco de papel en el escáner", "papel encravado no digitalizador", "замятие бумаги в сканере"),
 "the scanner is warming up — try again in a moment": ("le scanner chauffe — réessayez dans un instant", "der scanner wärmt auf — gleich noch einmal versuchen", "el escáner se está calentando — inténtelo en un momento", "o digitalizador está a aquecer — tente daqui a pouco", "сканер прогревается — попробуйте чуть позже"),
 "the connection to the scanner was interrupted": ("la liaison avec le scanner a été interrompue", "die verbindung zum scanner wurde unterbrochen", "la conexión con el escáner se interrumpió", "a ligação ao digitalizador foi interrompida", "связь со сканером прервалась"),
 "SANE is not installed (the scanner drivers)": ("SANE n'est pas installé (les pilotes de scanner)", "SANE ist nicht installiert (die scannertreiber)", "SANE no está instalado (los controladores de escáner)", "O SANE não está instalado (os controladores de digitalizador)", "SANE не установлен (драйверы сканера)"),
 "scan cancelled": ("scan annulé", "scan abgebrochen", "escaneo cancelado", "digitalização cancelada", "сканирование отменено"),
 "no scanner found — is it switched on?": ("aucun scanner trouvé — est-il allumé ?", "kein scanner gefunden — ist er eingeschaltet?", "no se encontró ningún escáner — ¿está encendido?", "nenhum digitalizador encontrado — está ligado?", "сканер не найден — он включён?"),
 "NAPS2 is not installed": ("NAPS2 n'est pas installé", "NAPS2 ist nicht installiert", "NAPS2 no está instalado", "O NAPS2 não está instalado", "NAPS2 не установлен"),
 "the scan did not work": ("le scan n'a pas marché", "der scan hat nicht geklappt", "el escaneo no funcionó", "a digitalização não funcionou", "сканирование не удалось"),
 "not a Reader's credentials file": ("ce n'est pas un fichier d'identifiants Reader's", "keine Reader's-zugangsdatendatei", "no es un archivo de credenciales Reader's", "não é um ficheiro de credenciais Reader's", "это не файл учётных данных Reader's"),
 "credentials imported": ("identifiants importés", "zugangsdaten importiert", "credenciales importadas", "credenciais importadas", "учётные данные импортированы"),
 "this file holds nothing for %1": ("ce fichier ne contient rien pour %1", "diese datei enthält nichts für %1", "este archivo no contiene nada para %1", "este ficheiro não contém nada para %1", "в этом файле нет ничего для %1"),
 "server and login taken from %1": ("serveur et identifiants repris de %1", "server und anmeldung aus %1 übernommen", "servidor y usuario tomados de %1", "servidor e utilizador retirados de %1", "сервер и логин взяты из %1"),
 "credentials exported to %1 — the file holds your passwords: keep it private": ("identifiants exportés dans %1 — le fichier contient vos mots de passe : gardez-le privé", "zugangsdaten nach %1 exportiert — die datei enthält ihre passwörter: halten sie sie privat", "credenciales exportadas a %1 — el archivo contiene sus contraseñas: manténgalo privado", "credenciais exportadas para %1 — o ficheiro contém as suas palavras-passe: mantenha-o privado", "учётные данные экспортированы в %1 — файл содержит ваши пароли: храните его в тайне"),
 "move earlier": ("avancer", "nach vorne", "mover antes", "mover para antes", "переместить раньше"),
 "move later": ("reculer", "nach hinten", "mover después", "mover para depois", "переместить позже"),
 "turn": ("tourner", "drehen", "girar", "rodar", "повернуть"),
 "delete this page": ("supprimer cette page", "diese seite löschen", "eliminar esta página", "eliminar esta página", "удалить эту страницу"),
 "page": ("page", "seite", "página", "página", "страница"),
 "discard": ("abandonner", "verwerfen", "descartar", "descartar", "отменить"),
 "name — optional: without one, the first words read on the page": ("nom — facultatif : sans nom, les premiers mots lus sur la page", "name — freiwillig: ohne namen die ersten gelesenen wörter der seite", "nombre — opcional: sin nombre, las primeras palabras leídas en la página", "nome — opcional: sem nome, as primeiras palavras lidas na página", "название — необязательно: без него — первые слова страницы"),
 "save": ("enregistrer", "speichern", "guardar", "guardar", "сохранить"),
 "look": ("aspect", "aussehen", "aspecto", "aspeto", "вид"),
 "text": ("texte", "text", "texto", "texto", "текст"),
 "1 blank page left out": ("1 page blanche écartée", "1 leere seite ausgelassen", "1 página en blanco apartada", "1 página em branco posta de parte", "1 пустая страница пропущена"),
 "%1 blank pages left out": ("%1 pages blanches écartées", "%1 leere seiten ausgelassen", "%1 páginas en blanco apartadas", "%1 páginas em branco postas de parte", "пустых страниц пропущено: %1"),
 "keep it": ("la garder", "behalten", "conservarla", "mantê-la", "оставить её"),
 "keep them": ("les garder", "behalten", "conservarlas", "mantê-las", "оставить их"),
 "1 page": ("1 page", "1 seite", "1 página", "1 página", "1 страница"),
 "%1 pages": ("%1 pages", "%1 seiten", "%1 páginas", "%1 páginas", "страниц: %1"),
 "all scans": ("tous les scans", "alle scans", "todos los escaneos", "todas as digitalizações", "все сканы"),
 "new folder": ("nouveau dossier", "neuer ordner", "nueva carpeta", "nova pasta", "новая папка"),
 "a click on a folder files the document there · Enter: « %1 »": ("un clic sur un dossier y range le document · Entrée : « %1 »", "ein klick auf einen ordner legt das dokument dort ab · Eingabe: « %1 »", "un clic en una carpeta guarda allí el documento · Intro: « %1 »", "um clique numa pasta guarda lá o documento · Enter: « %1 »", "щелчок по папке кладёт документ в неё · Enter: « %1 »"),
 "as scanned": ("tel que scanné", "wie gescannt", "tal como se escaneó", "como digitalizado", "как отсканировано"),
 "clean": ("net", "sauber", "limpio", "limpo", "чисто"),
 "grey": ("gris", "grau", "gris", "cinzento", "серый"),
 "b & w": ("n & b", "s/w", "b/n", "p/b", "ч/б"),
 "automatic": ("automatique", "automatisch", "automático", "automático", "автоматически"),
 "glass": ("vitre", "glas", "cristal", "vidro", "стекло"),
 "feeder": ("chargeur", "einzug", "alimentador", "alimentador", "лоток подачи"),
 "both sides": ("recto verso", "beidseitig", "doble cara", "frente e verso", "обе стороны"),
 "Tesseract best": ("Tesseract meilleur", "Tesseract bestes", "Tesseract mejor", "Tesseract melhor", "Tesseract лучший"),
 "A WebDAV folder shares the scans with your phone and your other computers: the same server, folder and login as in Reader's Scanner on Android. kDrive: server https://ID.connect.kdrive.infomaniak.com (the ID is the number in the kDrive web address), your Infomaniak login, and an application password if two-factor authentication is on. Nextcloud and any WebDAV server work the same way.": (
    "Un dossier WebDAV partage les scans avec votre téléphone et vos autres ordinateurs : le même serveur, le même dossier et les mêmes identifiants que dans Reader's Scanner sur Android. kDrive : serveur https://ID.connect.kdrive.infomaniak.com (l'ID est le nombre dans l'adresse web de kDrive), votre identifiant Infomaniak et un mot de passe d'application si la double authentification est active. Nextcloud et tout serveur WebDAV fonctionnent de la même façon.",
    "Ein WebDAV-ordner teilt die scans mit ihrem telefon und ihren anderen computern: derselbe server, ordner und login wie in Reader's Scanner auf Android. kDrive: server https://ID.connect.kdrive.infomaniak.com (die ID ist die zahl in der kDrive-webadresse), Ihr Infomaniak-login und bei zwei-faktor-anmeldung ein app-passwort. Nextcloud und jeder WebDAV-server funktionieren genauso.",
    "Una carpeta WebDAV comparte los escaneos con su teléfono y sus otros ordenadores: el mismo servidor, carpeta y usuario que en Reader's Scanner en Android. kDrive: servidor https://ID.connect.kdrive.infomaniak.com (el ID es el número de la dirección web de kDrive), su usuario de Infomaniak y una contraseña de aplicación si tiene la verificación en dos pasos. Nextcloud y cualquier servidor WebDAV funcionan igual.",
    "Uma pasta WebDAV partilha as digitalizações com o seu telemóvel e os seus outros computadores: o mesmo servidor, pasta e utilizador que no Reader's Scanner no Android. kDrive: servidor https://ID.connect.kdrive.infomaniak.com (o ID é o número no endereço web do kDrive), o seu utilizador Infomaniak e uma palavra-passe de aplicação se tiver a verificação em dois passos. O Nextcloud e qualquer servidor WebDAV funcionam da mesma forma.",
    "Папка WebDAV делит сканы с телефоном и другими компьютерами: тот же сервер, папка и логин, что в Reader's Scanner на Android. kDrive: сервер https://ID.connect.kdrive.infomaniak.com (ID — число в веб-адресе kDrive), ваш логин Infomaniak и пароль приложения при двухфакторной аутентификации. Nextcloud и любой WebDAV-сервер работают так же."),
 "server": ("serveur", "server", "servidor", "servidor", "сервер"),
 "username": ("identifiant", "benutzername", "usuario", "utilizador", "имя пользователя"),
 "password": ("mot de passe", "passwort", "contraseña", "palavra-passe", "пароль"),
 "folder on the server": ("dossier sur le serveur", "ordner auf dem server", "carpeta en el servidor", "pasta no servidor", "папка на сервере"),
 "import credentials…": ("importer les identifiants…", "zugangsdaten importieren…", "importar credenciales…", "importar credenciais…", "импортировать учётные данные…"),
 "export credentials…": ("exporter les identifiants…", "zugangsdaten exportieren…", "exportar credenciales…", "exportar credenciais…", "экспортировать учётные данные…"),
 "look again": ("chercher à nouveau", "noch einmal suchen", "buscar de nuevo", "procurar de novo", "искать снова"),
 "scanner": ("scanner", "scanner", "escáner", "digitalizador", "сканер"),
 "NAPS2 %1 — it talks to the scanner": ("NAPS2 %1 — c'est lui qui parle au scanner", "NAPS2 %1 — es spricht mit dem scanner", "NAPS2 %1 — es el que habla con el escáner", "NAPS2 %1 — é ele que fala com o digitalizador", "NAPS2 %1 — он общается со сканером"),
 "NAPS2 is not installed: it is required, it talks to the scanner.": ("NAPS2 n'est pas installé : il est indispensable, c'est lui qui parle au scanner.", "NAPS2 ist nicht installiert: es ist erforderlich, es spricht mit dem scanner.", "NAPS2 no está instalado: es imprescindible, es el que habla con el escáner.", "O NAPS2 não está instalado: é indispensável, é ele que fala com o digitalizador.", "NAPS2 не установлен: он необходим, он общается со сканером."),
 "automatic (%1 here)": ("automatique (%1 ici)", "automatisch (hier %1)", "automático (%1 aquí)", "automático (%1 aqui)", "автоматически (здесь %1)"),
 "A series (A4)": ("série A (A4)", "A-reihe (A4)", "serie A (A4)", "série A (A4)", "серия A (A4)"),
 "page format": ("format des pages", "seitenformat", "formato de página", "formato das páginas", "формат страниц"),
 "reading": ("lecture", "lesen", "lectura", "leitura", "чтение"),
 "font": ("police", "schrift", "fuente", "tipo de letra", "шрифт"),
 "cancel": ("annuler", "abbrechen", "cancelar", "cancelar", "отмена"),
 "Pierre Gallaz · developed with Claude Code": ("Pierre Gallaz · développé avec Claude Code", "Pierre Gallaz · entwickelt mit Claude Code", "Pierre Gallaz · desarrollado con Claude Code", "Pierre Gallaz · desenvolvido com Claude Code", "Pierre Gallaz · разработано с Claude Code"),
 "scanning by NAPS2, reading by Tesseract": ("scan par NAPS2, lecture par Tesseract", "scannen mit NAPS2, lesen mit Tesseract", "escaneo por NAPS2, lectura por Tesseract", "digitalização pelo NAPS2, leitura pelo Tesseract", "сканирование — NAPS2, чтение — Tesseract"),
 "none found yet": ("aucun trouvé pour l'instant", "noch keiner gefunden", "ninguno encontrado todavía", "nenhum encontrado ainda", "пока не найден"),
 "none found — is the scanner switched on?": ("aucun trouvé — le scanner est-il allumé ?", "keiner gefunden — ist der scanner eingeschaltet?", "ninguno encontrado — ¿está encendido el escáner?", "nenhum encontrado — o digitalizador está ligado?", "не найден — сканер включён?"),
 "looking…": ("recherche…", "suche…", "buscando…", "a procurar…", "поиск…"),
 "%1: downloading the best model… %2 %": ("%1 : téléchargement du meilleur modèle… %2 %", "%1: bestes modell wird geladen… %2 %", "%1: descargando el mejor modelo… %2 %", "%1: a descarregar o melhor modelo… %2 %", "%1: загрузка лучшей модели… %2 %"),
 "Reader's credentials (*.json)": ("Identifiants Reader's (*.json)", "Reader's-zugangsdaten (*.json)", "Credenciales Reader's (*.json)", "Credenciais Reader's (*.json)", "Учётные данные Reader's (*.json)"),
 "find": ("chercher", "suchen", "buscar", "procurar", "найти"),
 "the most accurate models (fetched once per language, 4 to 15 MB)": ("les modèles les plus exacts (téléchargés une fois par langue, 4 à 15 Mo)", "die genauesten modelle (einmal pro sprache geladen, 4 bis 15 MB)", "los modelos más precisos (descargados una vez por idioma, 4 a 15 MB)", "os modelos mais exatos (descarregados uma vez por língua, 4 a 15 MB)", "самые точные модели (загружаются один раз для языка, 4–15 МБ)"),
 "%1: the best model is here": ("%1 : le meilleur modèle est là", "%1: das beste modell ist da", "%1: el mejor modelo está aquí", "%1: o melhor modelo está cá", "%1: лучшая модель на месте"),
 "%1: the system's model for now": ("%1 : le modèle du système pour l'instant", "%1: vorerst das modell des systems", "%1: el modelo del sistema por ahora", "%1: o modelo do sistema por agora", "%1: пока модель системы"),
 "%1: its model will be fetched at the first reading": ("%1 : son modèle sera téléchargé à la première lecture", "%1: sein modell wird beim ersten lesen geladen", "%1: su modelo se descargará en la primera lectura", "%1: o modelo será descarregado na primeira leitura", "%1: модель загрузится при первом чтении"),
 "find in names and text": ("chercher dans les noms et le texte", "in namen und text suchen", "buscar en nombres y texto", "procurar nos nomes e no texto", "поиск по названиям и тексту"),
 "scan": ("scanner", "scannen", "escanear", "digitalizar", "сканировать"),
 "settings (Ctrl+,)": ("réglages (Ctrl+,)", "einstellungen (Strg+,)", "ajustes (Ctrl+,)", "definições (Ctrl+,)", "настройки (Ctrl+,)"),
 "open the PDF": ("ouvrir le PDF", "PDF öffnen", "abrir el PDF", "abrir o PDF", "открыть PDF"),
 "save a copy…": ("enregistrer une copie…", "kopie speichern…", "guardar una copia…", "guardar uma cópia…", "сохранить копию…"),
 "copy the text": ("copier le texte", "text kopieren", "copiar el texto", "copiar o texto", "копировать текст"),
 "from": ("depuis", "von", "desde", "de", "источник"),
 "automatic: the feeder when it holds paper, the glass otherwise": ("automatique : le chargeur s'il contient du papier, la vitre sinon", "automatisch: der einzug, wenn papier darin liegt, sonst das glas", "automático: el alimentador si tiene papel, el cristal si no", "automático: o alimentador se tiver papel, o vidro se não", "автоматически: лоток, если в нём бумага, иначе стекло"),
 "as scanned, or cleaned: white paper, grey, black and white": ("tel que scanné, ou nettoyé : papier blanc, gris, noir et blanc", "wie gescannt oder gereinigt: weisses papier, grau, schwarz-weiss", "tal como se escaneó, o limpiado: papel blanco, gris, blanco y negro", "como digitalizado, ou limpo: papel branco, cinzento, preto e branco", "как отсканировано или очищено: белая бумага, серый, чёрно-белый"),
 "the language the text is read in": ("la langue dans laquelle le texte est lu", "die sprache, in der der text gelesen wird", "el idioma en que se lee el texto", "a língua em que o texto é lido", "язык, на котором читается текст"),
 "reading the text %1": ("lecture du texte %1", "text wird gelesen %1", "leyendo el texto %1", "a ler o texto %1", "чтение текста %1"),
 "reading the text…": ("lecture du texte…", "text wird gelesen…", "leyendo el texto…", "a ler o texto…", "чтение текста…"),
 "text to be read": ("texte à lire", "text wird noch gelesen", "texto por leer", "texto por ler", "текст ещё не прочитан"),
 "text could not be read": ("le texte n'a pas pu être lu", "text konnte nicht gelesen werden", "no se pudo leer el texto", "não foi possível ler o texto", "текст не удалось прочитать"),
 "downloading… %1 %": ("téléchargement… %1 %", "wird geladen… %1 %", "descargando… %1 %", "a descarregar… %1 %", "загрузка… %1 %"),
 "scan not filed yet": ("scan pas encore rangé", "scan noch nicht abgelegt", "escaneo aún sin guardar", "digitalização ainda por arrumar", "скан ещё не разложен"),
 "nothing found": ("rien trouvé", "nichts gefunden", "no se encontró nada", "nada encontrado", "ничего не найдено"),
 "no scans here yet": ("pas encore de scan ici", "hier noch keine scans", "todavía no hay escaneos aquí", "ainda não há digitalizações aqui", "здесь пока нет сканов"),
 "rename…": ("renommer…", "umbenennen…", "cambiar el nombre…", "mudar o nome…", "переименовать…"),
 "delete the folder": ("supprimer le dossier", "ordner löschen", "eliminar la carpeta", "eliminar a pasta", "удалить папку"),
 "from files…": ("depuis des fichiers…", "aus dateien…", "desde archivos…", "de ficheiros…", "из файлов…"),
 "name of the new folder": ("nom du nouveau dossier", "name des neuen ordners", "nombre de la nueva carpeta", "nome da nova pasta", "название новой папки"),
 "new name of the folder": ("nouveau nom du dossier", "neuer name des ordners", "nuevo nombre de la carpeta", "novo nome da pasta", "новое название папки"),
 "Delete the folder “%1”? Its scans stay, in all scans.": ("Supprimer le dossier « %1 » ? Ses scans restent, dans tous les scans.", "Den ordner „%1“ löschen? Seine scans bleiben, in alle scans.", "¿Eliminar la carpeta «%1»? Sus escaneos se quedan, en todos los escaneos.", "Eliminar a pasta «%1»? As digitalizações ficam, em todas as digitalizações.", "Удалить папку «%1»? Её сканы останутся во «всех сканах»."),
 "put the pages on the scanner, press « scan »": ("posez les pages sur le scanner, appuyez sur « scanner »", "seiten auf den scanner legen, « scannen » drücken", "ponga las páginas en el escáner, pulse « escanear »", "ponha as páginas no digitalizador, carregue em « digitalizar »", "положите страницы в сканер и нажмите « сканировать »"),
 "In the feeder or on the glass: the scanner takes what it finds. The text is read on this computer, and the document becomes a PDF you can search.": ("Dans le chargeur ou sur la vitre : le scanner prend ce qu'il trouve. Le texte est lu sur cet ordinateur, et le document devient un PDF dans lequel on peut chercher.", "Im einzug oder auf dem glas: der scanner nimmt, was er findet. Der text wird auf diesem computer gelesen, und das dokument wird ein durchsuchbares PDF.", "En el alimentador o sobre el cristal: el escáner toma lo que encuentra. El texto se lee en este ordenador, y el documento se convierte en un PDF en el que se puede buscar.", "No alimentador ou no vidro: o digitalizador pega no que encontra. O texto é lido neste computador, e o documento torna-se um PDF pesquisável.", "В лотке или на стекле: сканер берёт то, что найдёт. Текст читается на этом компьютере, документ становится PDF с поиском."),
 "scan, or choose a document": ("scannez, ou choisissez un document", "scannen oder ein dokument wählen", "escanee o elija un documento", "digitalize ou escolha um documento", "сканируйте или выберите документ"),
 "Reader's Scanner needs NAPS2": ("Reader's Scanner a besoin de NAPS2", "Reader's Scanner braucht NAPS2", "Reader's Scanner necesita NAPS2", "O Reader's Scanner precisa do NAPS2", "Reader's Scanner нужен NAPS2"),
 "NAPS2 is the free program that talks to the scanner. It is installed separately, from naps2.com. Once it is there, « look again »; pictures and PDFs can be brought in from files meanwhile.": ("NAPS2 est le logiciel libre qui parle au scanner. Il s'installe à part, depuis naps2.com. Une fois installé, « chercher à nouveau » ; en attendant, des images et des PDF peuvent être apportés depuis des fichiers.", "NAPS2 ist das freie programm, das mit dem scanner spricht. Es wird separat installiert, von naps2.com. Danach « noch einmal suchen »; bis dahin lassen sich bilder und PDFs aus dateien holen.", "NAPS2 es el programa libre que habla con el escáner. Se instala aparte, desde naps2.com. Una vez instalado, « buscar de nuevo »; mientras tanto se pueden traer imágenes y PDF desde archivos.", "O NAPS2 é o programa livre que fala com o digitalizador. Instala-se à parte, a partir de naps2.com. Depois, « procurar de novo »; entretanto, imagens e PDFs podem vir de ficheiros.", "NAPS2 — свободная программа, которая общается со сканером. Она устанавливается отдельно, с naps2.com. После установки — « искать снова »; пока что изображения и PDF можно взять из файлов."),
 "get NAPS2": ("obtenir NAPS2", "NAPS2 holen", "obtener NAPS2", "obter o NAPS2", "получить NAPS2"),
 "scanned elsewhere": ("scanné ailleurs", "anderswo gescannt", "escaneado en otro lugar", "digitalizado noutro lado", "отсканировано в другом месте"),
 "pages": ("pages", "seiten", "páginas", "páginas", "страницы"),
 "No text was found on these pages.": ("Aucun texte n'a été trouvé sur ces pages.", "Auf diesen seiten wurde kein text gefunden.", "No se encontró texto en estas páginas.", "Não foi encontrado texto nestas páginas.", "На этих страницах текст не найден."),
 "The text has not been read yet.": ("Le texte n'a pas encore été lu.", "Der text wurde noch nicht gelesen.", "El texto todavía no se ha leído.", "O texto ainda não foi lido.", "Текст ещё не прочитан."),
 "its PDF needs the WebDAV folder": ("son PDF demande le dossier WebDAV", "sein PDF braucht den WebDAV-ordner", "su PDF necesita la carpeta WebDAV", "o PDF precisa da pasta WebDAV", "для PDF нужна папка WebDAV"),
 "the PDF is not on the server (any more)": ("le PDF n'est pas (plus) sur le serveur", "das PDF ist nicht (mehr) auf dem server", "el PDF no está (ya) en el servidor", "o PDF não está (já) no servidor", "PDF нет на сервере"),
 "save the copies in…": ("enregistrer les copies dans…", "kopien speichern in…", "guardar las copias en…", "guardar as cópias em…", "сохранить копии в…"),
 "save the pages as pictures in…": ("enregistrer les pages en images dans…", "seiten als bilder speichern in…", "guardar las páginas como imágenes en…", "guardar as páginas como imagens em…", "сохранить страницы как изображения в…"),
 "text copied": ("texte copié", "text kopiert", "texto copiado", "texto copiado", "текст скопирован"),
 "save the pages as pictures…": ("enregistrer les pages en images…", "seiten als bilder speichern…", "guardar las páginas como imágenes…", "guardar as páginas como imagens…", "сохранить страницы как изображения…"),
 "move to": ("déplacer vers", "verschieben nach", "mover a", "mover para", "переместить в"),
 "no folder (all scans only)": ("aucun dossier (tous les scans seulement)", "kein ordner (nur alle scans)", "sin carpeta (solo todos los escaneos)", "sem pasta (só todas as digitalizações)", "без папки (только «все сканы»)"),
 "edit the pages": ("modifier les pages", "seiten bearbeiten", "editar las páginas", "editar as páginas", "изменить страницы"),
 "add pages from the scanner": ("ajouter des pages depuis le scanner", "seiten vom scanner hinzufügen", "añadir páginas desde el escáner", "juntar páginas do digitalizador", "добавить страницы со сканера"),
 "read the text again in": ("relire le texte en", "text neu lesen auf", "volver a leer el texto en", "ler o texto de novo em", "прочитать текст заново на языке"),
 "delete": ("supprimer", "löschen", "eliminar", "eliminar", "удалить"),
 "sync now": ("synchroniser", "jetzt synchronisieren", "sincronizar ahora", "sincronizar agora", "синхронизировать"),
 "black on white": ("noir sur blanc", "schwarz auf weiss", "negro sobre blanco", "preto sobre branco", "чёрное на белом"),
 "white on black": ("blanc sur noir", "weiss auf schwarz", "blanco sobre negro", "branco sobre preto", "белое на чёрном"),
 "settings": ("réglages", "einstellungen", "ajustes", "definições", "настройки"),
 "name (empty: the first words of the text)": ("nom (vide : les premiers mots du texte)", "name (leer: die ersten wörter des textes)", "nombre (vacío: las primeras palabras del texto)", "nome (vazio: as primeiras palavras do texto)", "название (пусто — первые слова текста)"),
 "Delete “%1”?": ("Supprimer « %1 » ?", "„%1“ löschen?", "¿Eliminar «%1»?", "Eliminar «%1»?", "Удалить «%1»?"),
 "Delete these %1 documents?": ("Supprimer ces %1 documents ?", "Diese %1 dokumente löschen?", "¿Eliminar estos %1 documentos?", "Eliminar estes %1 documentos?", "Удалить эти документы (%1)?"),
 "scanning…": ("scan en cours…", "scannt…", "escaneando…", "a digitalizar…", "сканирование…"),
 "page %1": ("page %1", "seite %1", "página %1", "página %1", "страница %1"),
 "setting the pages upright…": ("remise à l'endroit des pages…", "seiten werden aufgerichtet…", "poniendo las páginas derechas…", "a endireitar as páginas…", "поворот страниц…"),
 "looking for the scanner…": ("recherche du scanner…", "scanner wird gesucht…", "buscando el escáner…", "a procurar o digitalizador…", "поиск сканера…"),
 "from the feeder": ("depuis le chargeur", "aus dem einzug", "desde el alimentador", "do alimentador", "из лотка подачи"),
 "from the glass": ("depuis la vitre", "vom glas", "desde el cristal", "do vidro", "со стекла"),
 "Put the pages in the feeder, or choose « glass ».": ("Mettez les pages dans le chargeur, ou choisissez « vitre ».", "Seiten in den einzug legen oder « glas » wählen.", "Ponga las páginas en el alimentador, o elija « cristal ».", "Ponha as páginas no alimentador, ou escolha « vidro ».", "Положите страницы в лоток или выберите « стекло »."),
 "Switch the scanner on and check its cable; then scan again.": ("Allumez le scanner et vérifiez son câble ; puis scannez à nouveau.", "Scanner einschalten und kabel prüfen; dann noch einmal scannen.", "Encienda el escáner y revise su cable; luego escanee de nuevo.", "Ligue o digitalizador e verifique o cabo; depois digitalize de novo.", "Включите сканер и проверьте кабель; затем сканируйте снова."),
 "scan again": ("scanner à nouveau", "noch einmal scannen", "escanear de nuevo", "digitalizar de novo", "сканировать снова"),
 "back to the pages": ("retour aux pages", "zurück zu den seiten", "volver a las páginas", "voltar às páginas", "назад к страницам"),
 "Discard this page?": ("Abandonner cette page ?", "Diese seite verwerfen?", "¿Descartar esta página?", "Descartar esta página?", "Отменить эту страницу?"),
 "Discard these %1 pages?": ("Abandonner ces %1 pages ?", "Diese %1 seiten verwerfen?", "¿Descartar estas %1 páginas?", "Descartar estas %1 páginas?", "Отменить эти страницы (%1)?"),
 "Pictures and PDFs": ("Images et PDF", "Bilder und PDFs", "Imágenes y PDF", "Imagens e PDF", "Изображения и PDF"),
 "bringing the pages in…": ("import des pages…", "seiten werden geholt…", "trayendo las páginas…", "a trazer as páginas…", "импорт страниц…"),
 "poppler-utils is needed to read a PDF": ("poppler-utils est nécessaire pour lire un PDF", "poppler-utils wird gebraucht, um ein PDF zu lesen", "se necesita poppler-utils para leer un PDF", "é preciso o poppler-utils para ler um PDF", "для чтения PDF нужен poppler-utils"),
 "nothing could be read in these files": ("rien n'a pu être lu dans ces fichiers", "in diesen dateien war nichts lesbar", "no se pudo leer nada en estos archivos", "não foi possível ler nada nestes ficheiros", "в этих файлах ничего не удалось прочитать"),
 "synced %1": ("synchronisé %1", "synchronisiert %1", "sincronizado %1", "sincronizado %1", "синхр. %1"),
 "no scanner found yet": ("pas encore de scanner", "noch kein scanner gefunden", "aún sin escáner", "ainda sem digitalizador", "сканер пока не найден"),
 "syncing…": ("synchronisation…", "synchronisiert…", "sincronizando…", "a sincronizar…", "синхронизация…"),
 "on this computer only": ("sur cet ordinateur seulement", "nur auf diesem computer", "solo en este ordenador", "só neste computador", "только на этом компьютере"),
 "Ctrl+, to set up a WebDAV folder shared with the phone": ("Ctrl+, pour configurer un dossier WebDAV partagé avec le téléphone", "Strg+, um einen mit dem telefon geteilten WebDAV-ordner einzurichten", "Ctrl+, para configurar una carpeta WebDAV compartida con el teléfono", "Ctrl+, para configurar uma pasta WebDAV partilhada com o telemóvel", "Ctrl+, — настроить папку WebDAV, общую с телефоном"),
}

_TR = {lang: {k: v[i] for k, v in _T.items()} for i, lang in enumerate(("fr", "de", "es", "pt", "ru"))}


def _lang():
    for var in ("LC_ALL", "LC_MESSAGES", "LANG"):
        v = os.environ.get(var)
        if v:
            return v[:2].lower()
    return system_locale()[:2].lower()


_LANG = _lang()
